version: 0.0
os: linux
# files:
#   - source: /index.html
#     destination: /var/www/html/
# hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: docker-compose up
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: docker-compose down
#       timeout: 300
#       runas: root