"""Add create_datetime to rosters

Revision ID: 35920d7d4f9f
Revises: de9f00c9b21c
Create Date: 2021-07-14 22:51:50.293086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35920d7d4f9f'
down_revision = 'de9f00c9b21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosters', sa.Column('create_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosters', 'create_datetime')
    # ### end Alembic commands ###
