"""add point value to roster

Revision ID: d02d959e495e
Revises: 35920d7d4f9f
Create Date: 2021-07-16 00:27:18.137434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02d959e495e'
down_revision = '35920d7d4f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rosters', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rosters', 'points')
    # ### end Alembic commands ###
